<?php include("header.phtml"); ?>

  <div class="col-xs-12">
    <div class="row">
      <div class="col-xs-12 m-b-2">
        <h2><?php print htmlentities($_GET["assunto"], ENT_QUOTES, 'utf-8'); ?></h2>
      </div>
    </div>

    <div class="row m-b-2">
      <div class="col-sm-12">
        <form class="form form-inline" method="get" action="/assunto.php">
          <input type="hidden" name="assunto" value="<?php print htmlentities($_GET["assunto"], ENT_QUOTES, 'utf-8') ?>">
          <div class="form-group">
            <label>Data de início:</label>
            <input type="date" name="inicio" class="form-control" value="<?php print date('Y-m-d', $inicio) ?>">
          </div>
          <div class="form-group">
            <label>Data de fim:</label>
            <input type="date" name="fim" class="form-control" value="<?php print date('Y-m-d', $fim) ?>">
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary">Visualizar</button>
          </div>
        </form>
      </div>
    </div>

    <div class="row m-b-2">
      <div class="col-xs-12">
        <div id="map" style="height:400px;"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="solicitacoes_por_dia"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="solicitacoes_por_subprefeitura"></div>
      </div>
    </div>
  </div>

<script>
new Chartist.Line('.solicitacoes_por_dia', {
    labels: [ <?php print implode(", ", $graficos['graphDays']['keys']) ?> ],
    series: [
      [ <?php print implode(", ", $graficos['graphDays']['values']); ?> ]
    ]
  }, {
    height: '250px'
});

new Chartist.Bar('.solicitacoes_por_subprefeitura', {
    labels: [ <?php print implode(", ", $graficos['graphSubprefeitura']['keys']) ?> ],
    series: [
      [ <?php print implode(", ", $graficos['graphSubprefeitura']['values']); ?> ]
    ]
  }, {
    height: '250px'
});

function initMap() {
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 10,
    center: {lng: -46.6532, lat: -23.5165}
  });

  var ctaLayer = new google.maps.KmlLayer({
    url: 'https://<?php print $_SERVER['SERVER_NAME'] ?>/assunto.php?output=kml&assunto=<?php print urlencode($_GET['assunto']) ?>&inicio=<?php print $inicio ?>&fim=<?php print $fim?>',
    map: map
  });
}
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?callback=initMap"></script>

<?php include("footer.phtml"); ?>