<?php include("header.phtml"); ?>

  <div class="col-xs-12">
    <div class="row">
      <div class="col-xs-12 m-b-2">
        <h2><?php 
          if (key($_GET)=="subprefeitura"):
            print $subprefeituras_keys[$_GET["subprefeitura"]];
          else:
            print $_GET[key($_GET)];
          endif;
        ?></h2>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="solicitacoes_por_dia"></div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="solicitacoes_por_subprefeitura"></div>
      </div>
    </div>
  </div>

<script>
new Chartist.Line('.solicitacoes_por_dia', {
    labels: [ <?php print implode(", ", $graficos['graphDays']['keys']) ?> ],
    series: [
      [ <?php print implode(", ", $graficos['graphDays']['values']); ?> ]
    ]
  }, {
    height: '250px'
});

new Chartist.Bar('.solicitacoes_por_subprefeitura', {
    labels: [ <?php print implode(", ", $graficos['graphSubprefeitura']['keys']) ?> ],
    series: [
      [ <?php print implode(", ", $graficos['graphSubprefeitura']['values']); ?> ]
    ]
  }, {
    height: '250px'
});
</script>

<?php include("footer.phtml"); ?>