
  <div id="rodape">
    <p><strong>Informações legais: </strong>SACSP não possui associação com a Prefeitura Municipal de São Paulo.
    Os dados aqui apresentados não são atualizados em tempo real.</p>
    <p class="links">
      <a href="/" class="contribua">Faça uma doação</a>
    </p>
  </div>

  <form id="pagseguro" target="pagseguro" action="https://pagseguro.uol.com.br/checkout/v2/donation.html" method="post">
    <input type="hidden" name="receiverEmail" value="bruno@mamulti.com.br" />
    <input type="hidden" name="currency" value="BRL" />
  </form>  

</div>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2659701-17', 'sacsp.info');
  ga('send', 'pageview');

</script>

</body>
</html>