<?php include("header.phtml"); ?>

  <div class="aviso">
  Contabilizando <?php print number_format($agregacoes['hits']['total'], 0, ",", ".") ?> solicitações entre
  <?php print date("d/m/Y H\hi", strtotime($data_minima['hits']['hits'][0]['_source']['timestamp'])) ?> até 
  <?php print date("d/m/Y H\hi", strtotime($agregacoes['hits']['hits'][0]['_source']['timestamp'])) ?>.
  </div>

  <div class="top10" id="topAssuntos">
    <h2>Top assuntos</h2>
    <table>
      <?php foreach($agregacoes['aggregations']['assunto']['buckets'] as $assunto): ?>
      <tr>
        <td class="titulo"><a href="/detalhe.php?assunto=<?php print urlencode($assunto['key']) ?>"><?php print $assunto['key'] ?></a></td>
        <td class="total"><?php print $assunto['doc_count'] ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>

  <div class="top10" id="topSubprefeituras">
    <h2>Top subprefeituras</h2>
    <table>
      <?php foreach($agregacoes['aggregations']['subprefeitura']['buckets'] as $subprefeitura): ?>
      <tr>
        <td class="titulo"><a href="/detalhe.php?subprefeitura=<?php print urlencode($subprefeitura['key']) ?>"><?php print isset($subprefeituras_keys[$subprefeitura['key']])?$subprefeituras_keys[$subprefeitura['key']]:$subprefeitura['key']?></a></td>
        <td class="total"><?php print $subprefeitura['doc_count'] ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>

  <span class="clear"></span>

  <div class="top10" id="topOrgaos">
    <h2>Top órgãos</h2>
    <table>
      <?php foreach($agregacoes['aggregations']['orgao']['buckets'] as $orgao): ?>
      <tr>
        <td class="titulo"><a href="/detalhe.php?orgao=<?php print urlencode($orgao['key']) ?>"><?php print $orgao['key'] ?></a></td>
        <td class="total"><?php print $orgao['doc_count'] ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>  

  <div class="top10" id="topCanais">
    <h2>Top canais de entrada</h2>
    <table>
      <?php foreach($agregacoes['aggregations']['canal']['buckets'] as $canais): ?>
      <tr>
        <td class="titulo"><a href="/detalhe.php?canal=<?php print urlencode($canais['key']) ?>"><?php print $canais['key'] ?></a></td>
        <td class="total"><?php print $canais['doc_count'] ?></td>
      </tr>
      <?php endforeach; ?>
    </table>
  </div>

<?php include("footer.phtml"); ?>